theme = "naz"

[editor]
line-number = "relative"
auto-save = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "position-percentage"]

[keys.normal]
"esc" = ["collapse_selection"]